apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  sourceDatabaseHost: {{ .Values.db.source.host | quote }}
  sourceDatabasePort: {{ .Values.db.source.port | default "5432" | quote }}
  sourceDatabaseName: {{ .Values.db.source.name | quote }}
  sourceDatabaseSchema: {{ .Values.db.source.schema | quote }}
  targetDatabaseHost: {{ .Values.db.target.host | quote }}
  targetDatabasePort: {{ .Values.db.target.port | default "5432" | quote }}
  targetDatabaseName: {{ .Values.db.target.name | quote }}
  timezone: {{ .Values.app.timezone | default "Europe/Zurich" | quote }}
