apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if ne .Values.keel.enabled false }}
  annotations:
    keel.sh/policy: {{ .Values.keel.policy | default "force" }}
    keel.sh/match-tag: {{ .Values.keel.matchTag | default "'true'" }}
    keel.sh/trigger: {{ .Values.keel.trigger | default "poll" }}
  {{- end }}
spec:
  schedule: "{{ .Values.app.schedule | default "0 0 * * *" }}"
  timeZone: "{{ .Values.app.timezone | default "Europe/Zurich" }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        spec:
          automountServiceAccountToken: false
          {{- if .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Release.Name }}
              image: ghcr.io/swisstopo/swissgeol-boreholes-suite-view-sync:{{ required "app.version is required" .Values.app.version }}
              imagePullPolicy: Always
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- if .Values.securityContext }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              {{- end }}
              env:
                - name: SOURCE_DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: sourceDatabaseHost
                - name: SOURCE_DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: sourceDatabasePort
                - name: SOURCE_DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: sourceDatabaseName
                - name: SOURCE_DB_SCHEMA
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: sourceDatabaseSchema
                - name: SOURCE_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabaseUsername
                - name: SOURCE_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: sourceDatabasePassword
                - name: TARGET_DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: targetDatabaseHost
                - name: TARGET_DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: targetDatabasePort
                - name: TARGET_DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: "{{ .Release.Name }}-config"
                      key: targetDatabaseName
                - name: TARGET_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabaseUsername
                - name: TARGET_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Release.Name }}-secrets"
                      key: targetDatabasePassword
          restartPolicy: Never
      backoffLimit: 4
