apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-legacy
  namespace: {{ .Release.Namespace }}
  {{- if ne .Values.keel.enabled false }}
  annotations:
    keel.sh/policy: {{ .Values.keel.policy | default "force" }}
    keel.sh/match-tag: {{ .Values.keel.matchTag | default "'true'" }}
    keel.sh/trigger: {{ .Values.keel.trigger | default "poll" }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-legacy
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-api-legacy
    spec:
      automountServiceAccountToken: false
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-api-legacy
          image: ghcr.io/swisstopo/swissgeol-boreholes-suite-api-legacy:{{ required "app.version is required" .Values.app.version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          livenessProbe:
            tcpSocket:
              port: 8888
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8888
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 8888
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 30
          resources:
            {{- toYaml .Values.resources.apiLegacy | nindent 12 }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: databaseHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: databasePort
                  optional: true
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: databaseName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: databaseUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: databasePassword
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: timezone
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-legacy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-api-legacy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
